/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConsultaDetalle;
import Controlador.ConsultaUsuario;
import Modelo.Manga;
import Modelo.Usuario;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author ConoMaster
 */
public class PanelVisualizarResumen extends javax.swing.JPanel {

    /**
     * Creates new form PanelResumen
     */
    
    Usuario seleccion;
    
    FramePrincipal frame;
    
    
    public PanelVisualizarResumen(FramePrincipal frame) {
        initComponents();
        this.frame = frame;
        listaUsuarios.setModel(modelListUsuarios());
        
        
        /*listaUsuarios.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(listaUsuarios.getSelectedValue()!= null){
                    System.out.println(listaUsuarios.getSelectedValue());
                    try {
                        
                        
                        
                        
                        
                        
                    } catch (SQLException ex) {
                        Logger.getLogger(PanelVisualizarResumen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
        */
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaMangas = new javax.swing.JList<>();

        jLabel1.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre usuario");

        listaUsuarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaUsuarios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaUsuariosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaUsuarios);

        listaMangas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaMangas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(194, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listaUsuariosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaUsuariosValueChanged
        try {
            listaUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            seleccion = (transformarStringUsuario(listaUsuarios.getSelectedValue()));
            ArrayList<Manga> mangas = ConsultaDetalle.listaMangas(seleccion);
            listaMangas.setModel(modelListManga(mangas));
            frame.panelUsuarioResumen = new PanelUsuarioResumen(seleccion);
            frame.setSize(1000, 1000);
            frame.add(frame.panelUsuarioResumen, BorderLayout.SOUTH);
            frame.panelUsuarioResumen.setVisible(true);
            frame.pack();
        } catch (SQLException ex) {
            Logger.getLogger(PanelVisualizarResumen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                        
    }//GEN-LAST:event_listaUsuariosValueChanged

    private DefaultListModel modelListUsuarios(){
        DefaultListModel model = new DefaultListModel<>();
        try {
            ArrayList<Usuario> usuarios = ConsultaUsuario.listaUsuarios();
            for(Usuario user : usuarios){
                model.addElement(user.getNombre());
            }
        } catch (SQLException ex) {
            Logger.getLogger(PanelVisualizarResumen.class.getName()).log(Level.SEVERE, null, ex);
        }
    return model;
    }
    
    private DefaultListModel modelListManga(ArrayList<Manga> mangas) throws SQLException{
        DefaultListModel model = new DefaultListModel<>();
            for(Manga manga : mangas){
                model.addElement(manga);
            }
    return model;
    }
    
    public Usuario transformarStringUsuario(String user) throws SQLException{
        ArrayList<Usuario> usuarios = ConsultaUsuario.listaUsuarios();
        for(Usuario u : usuarios){
            System.out.println(u);
        }
        System.out.println(usuarios);
        Usuario aux = null;
        for(Usuario u : usuarios){
            if(u.getNombre().contains(user)){
                aux = u;
            }
        }
        System.out.println("USUARIO SELECCIONADO");
        System.out.println(aux);
        return aux;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaMangas;
    private javax.swing.JList<String> listaUsuarios;
    // End of variables declaration//GEN-END:variables
}
